server:
  port: 8080

spring:
  main:
    allow-circular-references: true

keycloak:
  realm: my-realm
  resource: spring-boot-security
  auth-server-url: http://192.168.201.188:8080/auth
  ssl-required: external
  public-client: true
  principal-attribute: preferred_username

logging:
  level:
    org.keycloak: debug
    org.keycloak.adapters: debug