server:
  port: 8080

spring:
  main:
    allow-circular-references: true

keycloak:
  realm: my-realm
  resource: spring-boot-security-bearer
  auth-server-url: http://192.168.201.188:8080/auth
  bearer-only: true
  credentials:
    secret: 2ae3a35b-983a-42ff-bf6d-06a7268ca940
  ssl-required: external
  #  public-client: true
  principal-attribute: preferred_username
  connection-timeout: 6000

logging:
  level:
    org.keycloak: debug
    org.keycloak.adapters: debug