server:
  port: 8080

keycloak:
  # 声明客户端所在的realm
  realm: my-realm
  # 客户端名称
  resource: spring-boot-client
  # keycloak授权服务器的地址
  auth-server-url: http://192.168.201.188:8080/auth
  ssl-required: external
  # 声明这是一个公开的客户端，否则不能在keycloak外部环境使用，会403
  public-client: true
  security-constraints:
    - auth-roles:
        - admin
      security-collections:
        - patterns:
            - '/hello'

logging:
  level:
    org.keycloak: debug
    org.keycloak.adapters: debug