server:
  port: 10002

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.201.188:8080/auth/realms/my-realm
          jwk-set-uri: http://192.168.201.188:8080/auth/realms/my-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: service2
            client-secret: 4e1b3e2b-4082-4060-ae2f-1b297f73bf5f
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            authorization-uri: http://192.168.201.188:8080/auth/realms/my-realm/protocol/openid-connect/auth
            token-uri: http://192.168.201.188:8080/auth/realms/my-realm/protocol/openid-connect/token
            user-info-uri: http://192.168.201.188:8080/auth/realms/my-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://192.168.201.188:8080/auth/realms/my-realm/protocol/openid-connect/certs
            introspection-uri: http://192.168.201.188:8080/auth/realms/my-realm/protocol/openid-connect/token/introspect